#version: "3"
#
#services:
#  django:
#    restart: on-failure
#    build: .
#    container_name: scoolport
#    ports:
#      - "8000:8000"
#    command: >
#      sh -c '/usr/local/bin/python3 manage.py migrate --settings=$DJANGO_SETTINGS_MODULE && \
#            /usr/local/bin/python3 manage.py createsu --settings=$DJANGO_SETTINGS_MODULE && \
#            /usr/local/bin/python3 manage.py collectstatic --noinput --settings=$DJANGO_SETTINGS_MODULE && \
#            watchmedo auto-restart --directory=/scoolport/ --pattern=*.py --recursive -- \
#            /usr/local/bin/python3 manage.py runserver 0.0.0.0:$PORT --settings=$DJANGO_SETTINGS_MODULE'
#    env_file:
#      - .env
#    volumes:
#      - .:/scoolport
