# Generated by Django 5.0.7 on 2024-07-15 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='semester',
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registrations', to='portal.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='semesters', to='portal.session'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
