# Generated by Django 5.0.7 on 2024-09-29 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseregistration",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="course_registrations",
                to="portal.semester",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="courses",
                to="portal.semester",
            ),
        ),
    ]
