# Generated by Django 5.0.7 on 2024-09-29 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_user_email"),
        ("portal", "0002_courseregistration_semester_alter_course_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseregistration",
            name="level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="course_registrations",
                to="core.level",
            ),
        ),
    ]
