# Generated by Django 5.0.7 on 2024-07-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_course_course_code_alter_course_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='course',
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='course',
            field=models.ManyToManyField(related_name='registrations', to='portal.course'),
        ),
    ]
