# Generated by Django 5.0.7 on 2024-09-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_courseregistration_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="semester",
            options={"get_latest_by": "created"},
        ),
    ]
