# Generated by Django 5.0.7 on 2024-09-16 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_courseregistration_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registrations', to='portal.semester'),
        ),
    ]
