# Generated by Django 5.0.7 on 2024-09-16 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_studentprofile_matric_no_and_more'),
        ('portal', '0005_remove_courseregistration_semester_course_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseregistration',
            options={},
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='registered_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together={('student', 'course')},
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='course',
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registrations', to='portal.course'),
        ),
    ]
