# Generated by Django 5.0.7 on 2024-10-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_alter_coursegrade_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursegrade",
            name="grade",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("AR", "AR"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="coursegrade",
            name="point",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="result",
            name="grade",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("AR", "AR"),
                ],
                max_length=2,
            ),
        ),
    ]
