# Generated by Django 5.0.7 on 2024-10-06 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_alter_coursegrade_grade_alter_coursegrade_point_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseregistration",
            name="exam_score",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
