# Generated by Django 5.0.7 on 2024-09-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_course_course_code_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseregistration',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together=set(),
        ),
    ]
