# Generated by Django 5.0.7 on 2024-10-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_alter_courseregistration_exam_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursegrade",
            name="exam_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="coursegrade",
            name="point",
            field=models.IntegerField(null=True),
        ),
    ]
