# Generated by Django 5.0.7 on 2024-10-06 22:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_coursegrade_exam_score_alter_coursegrade_point"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("min_point", models.FloatField()),
                ("max_point", models.FloatField()),
            ],
            options={
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="remark",
            field=models.CharField(
                blank=True,
                choices=[("Passed", "Passed"), ("Failed", "Failed")],
                max_length=6,
                null=True,
            ),
        ),
    ]
