# Generated by Django 5.0.7 on 2024-10-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_gradelevel_courseregistration_remark"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradelevel",
            options={"ordering": ("created",)},
        ),
    ]
